---

- name: Install packages
  apt: name={{item}} state=latest
  with_items:
    - haproxy
    - openssl

- name: Allow binding to non-local addresses for transparent proxying
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: 1

- name: Setup IP route rules for transparent proxying
  register: service
  notify: [ip-routes]
  copy:
    src: ip-routes.service
    dest: /etc/systemd/system

- name: Enable IP route rules
  when: service|changed
  command: systemctl daemon-reload

- name: Place haproxy file
  template: src=haproxy.cfg dest=/etc/haproxy/haproxy.cfg
  register: haproxy

- name: Gen self signed cert, if no certs exist at all
  script: self_signed.sh creates=/etc/ssl/private/server.pem

- name: Ensure service is running at boot
  service: name=haproxy state=running enabled=true

- name: Restart haproxy if config changed
  service: name=haproxy state=restarted
  when: haproxy.changed
