---

- name: Install packages
  apt: name={{ item }} state=present
  with_items:
    - kvm
    - qemu-kvm
    - libvirt-bin
    - virtinst

- name: Create some dirs
  file: path={{ item }} state=directory
  with_items:
    - /var/lib/libvirt/isos
    - /var/lib/libvirt/configs
    - /var/cache/ansible/libvirt

- name: Copy libvirt config files
  template: src=hosts/{{item}} dest=/var/cache/ansible/libvirt
  with_items:
    - pilot.xml

- name: Setup DHCP configurations
  register: dnsmasq
  template:
    src: dhcp/{{item}}
    dest: /var/lib/dhcp/hosts
  with_items:
    - pilot

- name: Reload dnsmasq config
  when: dnsmasq|changed
  shell: kill -HUP $(cat /var/run/dnsmasq/dnsmasq.pid) || true

- name: Destroy libvirt default network
  command: virsh net-undefine default
  register: net_destroy
  failed_when: >
    net_destroy.rc != 0 and ("Network not found" not in net_destroy.stderr)
  changed_when: >
    net_destroy.rc == 0

- name: Load pilot config file
  command: virsh define /var/cache/ansible/libvirt/pilot.xml 
