---

- name: Install packages
  apt: name={{ item }} state=present
  with_items:
    - kvm
    - qemu-kvm
    - libvirt-bin
    - virtinst

- name: Create some dirs
  file: path={{ item }} state=directory
  with_items:
    - /var/lib/libvirt/isos
    - /var/lib/libvirt/configs
    - /var/cache/ansible/libvirt

- name: Copy libvirt config files
  template: src=hosts/{{item}} dest=/var/cache/ansible/libvirt
  with_items:
    - pilot.xml

- name: Define static IP for pilot
  command: virsh net-update --network default --command add-last --section ip-dhcp-host --xml "<host mac='{{moya.vm_net.pilot.mac}}' name='pilot.trilug.org' ip='{{moya.vm_net.pilot.ipv4}}'/>"
  register: net_define
  changed_when: net_define.rc == 0
  failed_when: >
    net_define.rc != 0 and ("there is an existing" not in net_define.stderr)

- name: Destroy libvirt network
  command: virsh net-destroy default
  register: net_destroy
  when: net_define|succeeded
  failed_when: >
    net_destroy.rc != 0 and ("is not active" not in net_destroy.stderr)

- name: Start libvirt network
  command: virsh net-start default
  when: net_define|succeeded

- name: Load pilot config file
  command: virsh define /var/cache/ansible/libvirt/pilot.xml 
