---
- name: Create interface config file
  register: config
  template:
    src: br-guest.conf
    dest: /etc/network/interfaces.d

- name: Enable interface
  when: config|changed
  shell: ifdown br-guest; ifup br-guest

- name: Add sysctl file to enable IPv4 forwarding
  register: sysctl
  template:
    src: ip-forward.conf
    dest: /etc/sysctl.d
- name: Enable IPv4 forwarding
  when: sysctl|changed
  command: sysctl -p

- name: Create DHCP hosts directory
  file:
    path: /var/lib/dhcp/hosts
    state: directory

- name: Create dnsmasq config file
  notify: [dnsmasq]
  template:
    src: dnsmasq.conf
    dest: /etc

- name: Install dnsmasq
  apt:
    name: dnsmasq
